orbs:
  tutorial-checker-orb: saptutorials/tutorial-checker@1.0.0
version: 2.1
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/15f197634234d80a32fa
workflows:
  version: 2
  nightly:
    triggers:
    - schedule:
        cron: "0 0 * * 0-5"
        filters:
          branches:
            only:
              - main
    jobs:
      - tutorial-checker-orb/build-all:
          env: 'NODE_ENV=stage'
  commitly:
    jobs:
      - tutorial-checker-orb/build-last-commit:
          env: 'NODE_ENV=stage'
